version: "3.8"

services:
  db-postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8npass
      POSTGRES_DB: n8ndb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data 

  n8n:
    build: .
    restart: always
    environment:
      GENERIC_TIMEZONE: America/Sao_Paulo
      TZ: America/Sao_Paulo
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: db-postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8ndb
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8npass
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - db-postgres

volumes:
  db_data:
  n8n_data: